/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.arturkufa;

import picocli.CommandLine;
import pl.arturkufa.pack.CompressUtilityCommand;
import pl.arturkufa.text.TextCommand;

import java.util.stream.Stream;

public class App {
    public static void main(String[] args) {
        int exitCode = 0;
        try {
            exitCode = new CommandLine(new CompressUtilityCommand()).execute(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.exit(exitCode);
    }
}
